name: neobez
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  intl: ^0.19.0
  csv: ^5.0.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_png.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/app_png.png
    - lib/assets/turkish_food_dataset_1.csv
